### ISSUE TITLE
Use -data switch for inline and file bodies

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMClient#1]
Let's follow the curl convention:

- To pass a body inline: `--data "{qqq: '111' }"`
- To pass a body from a file: `--data @"sub\body.json"`

So just looking at whether the first char is an `@` is the determinant.

**Comment by suwatch** [comment]
Fixed by https://github.com/projectkudu/ARMClient/commit/1c1681d776f515f3db3518826b4b84310d7202e8

The drawback of `@file` is we lost auto-completion on file name and path.
