### ISSUE TITLE
Issue with simple GET

### ISSUE THREAD

**Issue by wadewegner** [projectkudu/ARMClient#10]
I followed the docs and ran `armclient spn ...` and got the following output:

    There are 1 subscriptions
    Subscription 56e48470... (My Subscription)

So far so good. Then I tried a simple sample from @davidebbo's post:

    armclient GET /subscriptions?api-version=2014-04-01

The output I get is as follows:

    Only 'http' and 'https' schemes are allowed.
    Parameter name: requestUri

Hope I haven't misunderstood!

**Comment by davidebbo** [comment]
To isolate whether it's spn related, does it work if you use regular login? i.e. run `armclient clearcache` and then directly run your GET command, which will prompt you to log in.

**Comment by davidebbo** [comment]
Also, makes sure you have the latest tool: 0.9.1 (or later). In the earlier one, the hostname was not optional. Come to think of it, that's much more likely to be your issue :)

**Comment by wadewegner** [comment]
Note: running the following command works:

    armclient get https://management.azure.com/subscriptions?api-version=2014-04-01

I get the expected Json emitted.

**Comment by davidebbo** [comment]
Yes, you definitely have the old one. Run it without params to get the ver.

**Comment by wadewegner** [comment]
I installed from Chocolatey: `choco install armclient`

No version flag to check which version. Is the latest pushed to Chocolatey?

**Comment by davidebbo** [comment]
What version to do you have? Maybe some choco weirdness gave you 9.0?

**Comment by wadewegner** [comment]
I still had the output in my console:

![choco](https://cloud.githubusercontent.com/assets/746259/5828736/08b10f54-a0c5-11e4-8590-c81dc003f821.png)

Looks to me like 0.9.1.

**Comment by davidebbo** [comment]
Ok, let me delete mine and re-get it from chocolatey.

**Comment by ahmelsayed** [comment]
it might be bash weirdness with leading `/`. Can you try with `cmd.exe`

**Comment by davidebbo** [comment]
Ah good call @ahmelsayed , I bet that's it!

**Comment by wadewegner** [comment]
Ah, this slash issue again? =)

From `cmd.exe` it works as expect. 
From `msys/cygwin` it works when changed to: `armclient get \subscriptions?api-version=2014-04-01`

Thanks for the quick response and sorry for the trouble!

**Comment by davidebbo** [comment]
Those slash issues are ugly :(
