### ISSUE TITLE
Request url parsing issue with multiple query string parameters

### ISSUE THREAD

**Issue by IlyaGrebnov** [projectkudu/ARMClient#11]
I am getting error "'top' is not recognized as an internal or external command, operable program or batch file." for following command. Looks like problem with request url parsing with multiple query string parameters.

ARMClient.exe GET /subscriptions/26756605-1ad6-450f-b87f-6ccc2acd0ebc/resourceGroups?api-version=2014-04-01-preview&top=1 -verbose

**Comment by ahmelsayed** [comment]
you need to escape `&` on cmd. You can either surround the URL with `" "` or use `^&`

**Comment by davidebbo** [comment]
Yes, this is unrelated to this tool. Generally, cmd interprets `&` as having too separate commands that need to be run. Quoting the path is the simplest approach.
