### ISSUE TITLE
Documentation .net example

### ISSUE THREAD

**Issue by iremmats** [projectkudu/ARMClient#18]
Hi,

The documentation to create the DynamicClient is a bit off after the commit made 30th jan.

**Comment by davidebbo** [comment]
Any chance you can send a PR with the suggested readme.md change? Note that `DynamicClient` is very much experimental at this point.

**Comment by iremmats** [comment]
Hi,

Created a PR for it.

I was about to try creating a client for this myself but well, cool someone else already had written one. :)

Use case was automatic way to find empty ResourceGroups and delete them.
______________________________
Mats Iremark, Cloud Architect @ e-man AB
Tel: 0708-194243

Från: David Ebbo <notifications@github.com<mailto:notifications@github.com>>
Svara till: projectkudu/ARMClient <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Saturday 18 July 2015 06:18
Till: projectkudu/ARMClient <ARMClient@noreply.github.com<mailto:ARMClient@noreply.github.com>>
Kopia: Mats Iremark <mats.iremark@e-man.se<mailto:mats.iremark@e-man.se>>
Ämne: Re: [ARMClient] Documentation .net example (#18)


Any chance you can send a PR with the suggested readme.md change? Note that DynamicClient is very much experimental at this point.

-
