### ISSUE TITLE
Make server optional in URL

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMClient#2]
e.g. instead of:

    ARMClient.exe get https://management.azure.com/subscriptions/92685311-fa5d-4d8b-9f7c-7cae01660c9d/providers/Microsoft.Web?api-version=2014-04-01

let's allow

    ARMClient.exe get /subscriptions/92685311-fa5d-4d8b-9f7c-7cae01660c9d/providers/Microsoft.Web?api-version=2014-04-01

Note that we still want to allow passing the server name if user chooses. We're just making it optional.

**Comment by suwatch** [comment]
Fixed by https://github.com/projectkudu/ARMClient/commit/d6856e827a205d2864ca462a03c578e2b036354a
