### ISSUE TITLE
spn login tenantid

### ISSUE THREAD

**Issue by pjirsa** [projectkudu/ARMClient#20]
The tenant ID can be either a GUID or mydomain.onmicrosoft.com. Could you please remove the EnsureGuidFormat(tenantID) on line 88 of Program.cs?

Thanks

**Comment by suwatch** [comment]
Fixed by https://github.com/projectkudu/ARMClient/commit/b1d50afd29991adb0bbf51ab2759538f5e47b512  
@pjirsa I have done a few sanity tests.  If you could verify your scenario as well, it would be great.
