### ISSUE TITLE
Can's use ARMCient with VSO

### ISSUE THREAD

**Issue by suwatch** [projectkudu/ARMClient#23]
@suwatch I try to use ARMClient for VSO, but any request from ARMClient to VSO like ARMClient.exe get "https://app.vssps.visualstudio.com/_apis/profile/profiles/me?api-version=1.0" return the authentication page. In some time all requests to SCM like: ARMClient.exe get "/subscriptions?api-version=2014-04-01" is successful and return JSON.

ARMClient is authenticated in Azure through ARMClient.exe login and my VSO account is linked to my Azure account. Is this bug or I doing something wrong? Maybe better is forwarding this question to ARMClient Issues?

**Comment by suwatch** [comment]
I just tried and it worked fine for me (meaning return json).

`ARMClient.exe get "https://app.vssps.visualstudio.com/_apis/profile/profiles/me?api-version=1.0"`

@denisyfrolov, did you build ARMClient or get it thru chocolatey?

**Comment by denisyfrolov** [comment]
@suwatch I get it thru chocolatey.

**Comment by suwatch** [comment]
It works fine for me.  I also get thru chocolatey  armclient.  The latest version of armclient is 1.0.3.  Can you make sure it is the same?

**Comment by denisyfrolov** [comment]
ARMClient version 1.0.3.0

Maybe it is better to build it from source?

**Comment by denisyfrolov** [comment]
[Imgur](http://i.imgur.com/7o7BLyk.jpg?1) here my subscriptions, maybe problem in that I have several subscriptions? How I can specify subscription for access to VSO?

**Comment by suwatch01** [comment]
Run `armclient token <tenantId>` to switch to different tenant that subscriptions belong to.   TenantId is guid, you can see by running `armclient listcache`.   More info [here](https://github.com/projectkudu/ARMClient/wiki/Login-and-Acquire-Tokens).

**Comment by denisyfrolov** [comment]
Yep, it helped. Thanks!

**Comment by suwatch** [comment]
Alright then.  I will close it for now.
