### ISSUE TITLE
add-cred hardcodes client certificate endDate to now + 1 year

### ISSUE THREAD

**Issue by maitre-matt** [projectkudu/ARMClient#26]
ARMClient.Program.GetPatchContent() ignores the actual end-date of the client certificate and uses 1 year instead. We use 2-year certificates and add-cred's unexpected behavior triggered an outage.

**Comment by snobu** [comment]
For context:
https://github.com/projectkudu/ARMClient/blob/master/AADClient.Console/Program.cs#L361
