### ISSUE TITLE
Add optional parameter to send custom HTTP headers

### ISSUE THREAD

**Issue by snobu** [projectkudu/ARMClient#27]
Would be great to have a _curl_ like `-H` parameter to add custom HTTP headers to requests.

i.e.
```cmd
C:\>ARMClient.exe get https://acc.blob.core.windows.net/container/blob -H "Range: bytes=3744-"

---------- Request -----------------------

GET /container/blob HTTP/1.1
Host: acc.blob.core.windows.net
Authorization: Bearer eyJ0eXAiOiJKV...
User-Agent: ARMClient/1.1.1.0
[...]
Range: bytes=3744-
```

This is actually the worst example since Azure Storage expects a SAS as authorization, but... the point still stands :)

**Comment by davidebbo** [comment]
Indeed, for storage, it's all in the data plane and not control plane.

Generally, it would be fine to add that, though might be good to have a valid scenario to drive it :)

**Comment by snobu** [comment]
Added in https://github.com/projectkudu/ARMClient/commit/0fafe128a3be09af20dbb3c2f47d8904fb4cd7d7 by @suwatch. Thanks @suwatch!

I promise i'll find real use for this feature. I think @suwach already has a use case, and if he doesn't, ..then we're overcontributing. Yes, that's a word :)
