### ISSUE TITLE
Unable to install Armclient

### ISSUE THREAD

**Issue by kapil-ms** [projectkudu/ARMClient#29]
I am unable to install Armclient. The error is attached.
I am using Powershell in administrator mode and have the latest version of chocolatey installed.
![armclient](https://cloud.githubusercontent.com/assets/20193720/22605303/1f352654-ea04-11e6-9dec-c6571984c13d.PNG)

**Comment by davidebbo** [comment]
Strange, it works for me. More likely to be Chocolatey issue than arm client, since at that point it hasn't run at all.

BTW, please paste **text** instead of screenshot whenever possible, as it makes it much easier to search for.

**Comment by davidebbo** [comment]
See https://github.com/chocolatey/choco#submitting-issues
