### ISSUE TITLE
Make login automatic

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMClient#3]
Today, if you make a request before logging in, it blows up badly, e.g.

    Could not find file 'C:\Users\david\.arm\recent_token.dat'

Of course, we could clean up the error handling, but it would be even better to simply login on demand if we don't have a token cache.

We can still keep the login command for PPE envs.

**Comment by suwatch** [comment]
Fixed by https://github.com/projectkudu/ARMClient/commit/93d3915fdc5b637662d4e6aaaf0df1a2b2fb44b5
