### ISSUE TITLE
Please make a github release available with pre-built binaries

### ISSUE THREAD

**Issue by leidegre** [projectkudu/ARMClient#33]
...not really interested in installing yet another package manager.

**Comment by davidebbo** [comment]
We're trying to stay away from having two different distribution channels and having to keep both up to date. So I don't think we'll do this unless there is a lot of demand for it from community (it has not come up before afaik).

**Comment by leidegre** [comment]
Well, I can try. I ended up downloading and just building the source, that wasn't really a big problem. So it's fine. I was just cranky. Yesterday. Spent all day troubleshooting.

**Comment by davidebbo** [comment]
Yep, it's easy enough to build, and let's you hack on it if you're so inclined :)
