### ISSUE TITLE
Run inside VSTS task

### ISSUE THREAD

**Issue by leidegre** [projectkudu/ARMClient#34]
Is there any way you can run inside a VSTS task?

You can have PowerShell and Azure CLI running with an account that is provided by the VSTS environment can the same be made possible with `ARMClient`?

I _really_ **really** don't want to have to setup service principals...

**Comment by davidebbo** [comment]
That sounds more like a VSTS question than ARMClient. If you can bring ARMClient to the VSTS build machine, then I suspect it would run fine from there.

**Comment by leidegre** [comment]
Yes, naturally, but it depends entirely on how it manages credentials. Trying to figure out that right now.

**Comment by leidegre** [comment]
From VSTS release process

~~~
[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u ******** -p ******** --tenant ********"
2017-09-22T08:12:21.8913292Z [
2017-09-22T08:12:21.8923289Z   {
2017-09-22T08:12:21.8923289Z     "cloudName": "AzureCloud",
2017-09-22T08:12:21.8923289Z     "id": "1c4992c2-c303-4972-8122-8d3a28201cd9",
2017-09-22T08:12:21.8923289Z     "isDefault": true,
2017-09-22T08:12:21.8923289Z     "name": "Pay-As-You-Go",
2017-09-22T08:12:21.8923289Z     "state": "Enabled",
2017-09-22T08:12:21.8923289Z     "tenantId": "********",
2017-09-22T08:12:21.8923289Z     "user": {
2017-09-22T08:12:21.8923289Z       "name": "********",
2017-09-22T08:12:21.8923289Z       "type": "servicePrincipal"
2017-09-22T08:12:21.8923289Z     }
2017-09-22T08:12:21.8923289Z   }
2017-09-22T08:12:21.8923289Z ]
~~~

It signs you in using a service principal, is there anyway `ARMClient` can pick up that?

**Comment by davidebbo** [comment]
I see, so you mean make it work so if you're already logged in via 'az' tool, armclient would automatically pick that up? It doesn't do that, but if you already have the service principal info, that you use for az, why not pass the same thing to armclient? https://github.com/projectkudu/ARMClient/wiki/Using-Service-Principal-(spn)

**Comment by leidegre** [comment]
It's injected very secretively by the VSTS environment, maybe there's a task that let me customize this but I haven't found it.

Thanks, I'll keep digging.

**Comment by leidegre** [comment]
@davidebbo btw, this tool is exactly what I've been looking for all along.

**Comment by snobu** [comment]
P.S. `az` can now call raw into ARM API as well:

e.g.
```
az resource show --id /subscriptions/axxxxxxxx/resourceGroups/amisecure/providers/Microsoft.Web/sites/amisecure/config/web --api-version 2016-08-01

az resource update --id /subscriptions/axxxxxxxxxx/resourceGroups/amisecure/providers/Microsoft.Web/sites/amisecure/config/web --api-version 2016-08-01 --set properties.key=value
```

Use https://resources.azure.com/ to build the request (there's an **Azure CLI 2.0** tab in there).

**Comment by leidegre** [comment]
@snobu 👍 nice! though, you should know, I still like this tool better but I can't afford to waste more time trying to find a way to make credentials work within VSTS, so this will have to do. Thanks!

**Comment by davidebbo** [comment]
Yes, I pushed hard on them to support that :). Not quite as powerful yet. e.g. you wouldn't be able to call an action, like to restart a site. Though that's coming. See https://github.com/Azure/azure-cli/pull/4509

**Comment by leidegre** [comment]
@davidebbo what I wanted all along was something that allowed me to consume the ARM APIs without dragging in a gazillion of DLLs, so this ARMClient is small and nimble enough that I can easily integrate it with my own tooling. Right now, I'm using shell execute to interop with Azure CLI because it's the only thing that I can reliably get to work everywhere...

**Comment by leidegre** [comment]
@snobu actually that's not enough. I need to be able to just do the freaking PUT operation of the raw JSON structure directly. I noticed that the Azure CLI is subject to race conditions, I'm just trying to push a bunch of appsettings but all the strings are too long to perform as a single op so I run them in parallel but I think they overwrite each other because only half of them get written.

**Comment by snobu** [comment]
I don't believe the ARM API supports parallel PUTs on the same set of App Settings. @davidebbo can confirm. Remember that all you really need is to get your hands on a `Bearer` token, then you can just `HttpClient` your way around ARM, without extra dependencies (well, except for ADAL).

```
   var credential = new UserCredential(username, password);
   var result = context.AcquireTokenAsync(resource, clientId, credential);
```

**Comment by leidegre** [comment]
From my testing, I would say it does not which of course makes sense because I'm assuming it's doing PUT over the same resource. Right now all my settings are 1600 characters, which is OK but I don't want to be hitting the 8000 character limit of the command line and have settings truncated without warning. I've been trying to use the CLI to just push some settings from a file but apparently, you cannot pass input as a file or through stdin. And the whole reason for doing it in parallel is because I don't want to wait longer than necessary...

**Comment by snobu** [comment]
You have an Azure PowerShell task for that in VSTS:
![image](https://user-images.githubusercontent.com/6472374/30762241-e076e9b0-9fe9-11e7-91cc-7987b52ee0c1.png)
Define the App Settings as environment variables and pick them up in the `.ps1` script.

**Comment by leidegre** [comment]
OK but the PowerShell RM module isn't very fun to work with because it doesn't remember your login between sessions, like CLI does. And now I have two sets of shells to manage as well, which only do the REST part which I would like to do my self actually but I cannot see how I do that because I need to create a service principal for that yet, somehow this is not necessary with the VSTS, PowerShell RM or CLI.

**Comment by snobu** [comment]
You should see the VSTS Service Principal in your subscription in the Azure Portal, under your Web App, however i'm not sure if you can see its password.

![image](https://user-images.githubusercontent.com/6472374/30762825-3b625510-9fec-11e7-88f7-1d0783f901d0.png)

Just [create a service principal](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?toc=%2Fazure%2Fazure-resource-manager%2Ftoc.json&view=azure-cli-latest), allocate a quiet 10 minutes, it's really not difficult, it's the answer to all your trouble.

**Comment by leidegre** [comment]
I can drop our production database but I cannot create an app in our AD, *sigh*. Yet I am an administrator of our subscription. At some future point maybe I will resolve this as well but I shouldn't have to jump through this many hops.
