### ISSUE TITLE
Windows 10 crash on login

### ISSUE THREAD

**Issue by Onefox** [projectkudu/ARMClient#37]
After:
`choco install armclient`

when i try `armclient login`  the login window opens but the armclient.exe finds an exeption and windows closes the process...

armclient spn is working as expected.

Is there a log file that gets generated that i can provide you?

**Comment by davidebbo** [comment]
It works for me. I'm thinking it could be some browser related issue.

Note that for quick testing ARM command, you can also use https://resources.azure.com/raw, which takes care of the login part.

**Comment by Onefox** [comment]
I have the newest chrome as a default browser, the Microsoft login window is working on other applications like visual studio for example.

Since the application is throwing an exception could it be that there is some error handling missing, or are errors written to a log file somewhere?

**Comment by davidebbo** [comment]
I think this always uses IE to pop up the auth window. Right @suwatch?

**Comment by suwatch** [comment]
It is the IE (AAD library launching it).  

@Onefox ARMClient (console application) should spew out the error on the console (see this [try/catch](https://github.com/projectkudu/ARMClient/blob/master/ARMClient.Console/Program.cs#L26)).   Try setting env  `ARMCLIENT_VERBOSE=1` to see more verbose error.   Also try if repro-able on a different computer.

**Comment by Onefox** [comment]
mmmh somehow after i used the spn login now the armclient login is working... 
Sadly i was not able to see any errors, there were nothing in the console. The last time it crashed.
