### ISSUE TITLE
can't install armclient

### ISSUE THREAD

**Issue by jeffrey-ACE** [projectkudu/ARMClient#38]
C:\windows\system32>choco install armclient
Chocolatey v0.10.8
Installing the following packages:
armclient
By installing you accept licenses for the packages.
armclient not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://wanuget/bootstrap/nuget"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - armclient - armclient not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://wanuget/bootstrap/nuget"

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare

**Comment by davidebbo** [comment]
It could have been some temporary chocolatey condition, and nothing specific to ARMClient.

- Are you still seeing this?
- If so, are you able to install anything at all from chocolatey?

**Comment by jeffrey-ACE** [comment]
You are right, I am not able to install anything from chocolatey.

**Comment by shis-microsoft** [comment]
Hi, 
I am also facing similar issue 

C:\WINDOWS\system32> choco install armclient
Installing the following packages:
armclient
By installing you accept licenses for the packages.
armclient not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://wanuget/bootstrap/nuget"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - armclient - armclient not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://wanuget/bootstrap/nuget"


is there any alternate way to install armclient without using chocolatey

**Comment by davidebbo** [comment]
@shis-microsoft why is your package source set to http://wanuget/bootstrap/nuget? It should be https://chocolatey.org/api/v2/. e.g.

```
C:\Windows\System32>choco sources
Chocolatey v0.10.8
chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
```

**Comment by jeffrey-ACE** [comment]
@shis-microsoft  try this: choco install armclient -source https://chocolatey.org/api/v2/

**Comment by davidebbo** [comment]
@jeffrey-ACE that should do it. But why would it be picking up that random other (intranet) source unless something explicitly registered it with Chocolatey?

**Comment by jeffrey-ACE** [comment]
@davidebbo We need run some powershell script before enlist our source code, I think the powershell script did that.

**Comment by shis-microsoft** [comment]
Thanks @davidebbo  and @jeffrey-ACE  it worked :)
