### ISSUE TITLE
can't install armclient from chocolatey

### ISSUE THREAD

**Issue by shis-microsoft** [projectkudu/ARMClient#40]
Hi,
I am facing below issue when trying to install armclient:

C:\WINDOWS\system32> choco install armclient
Installing the following packages:
armclient
By installing you accept licenses for the packages.
armclient not installed. The package was not found with the source(s) listed.
If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
Version: ""
Source(s): "http://wanuget/bootstrap/nuget"

Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures

armclient - armclient not installed. The package was not found with the source(s) listed.
If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
Version: ""
Source(s): "http://wanuget/bootstrap/nuget"

Can someone help me how to fix it and is there any alternate way to install armclient without using chocolatey?

**Comment by davidebbo** [comment]
Copying my comment from #38:

@shis-microsoft why is your package source set to http://wanuget/bootstrap/nuget? It should be https://chocolatey.org/api/v2/. e.g.

```
C:\Windows\System32>choco sources
Chocolatey v0.10.8
chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
```

**Comment by shis-microsoft** [comment]
@davidebbo  thanks...  I noticed that some other process in my system had disabled source https://chocolatey.org/api/v2/ in chocolatey.config  that's why it was picking up other sources and failing.
