### ISSUE TITLE
Can't run ARMClient: This app can't run on your PC

### ISSUE THREAD

**Issue by pvrk** [projectkudu/ARMClient#42]
I have run ARMClient before in my PC but it suddenly stopped saying "This app can't run on your PC". Following are my PC settings: Please help

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	PVRKAR
System Manufacturer	LENOVO
System Model	20FAS2K13B
System Type	x64-based PC
System SKU	LENOVO_MT_20FA_BU_Think_FM_ThinkPad T460s
Processor	Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 2808 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO N1CET63W (1.31 ), 12/19/2017
SMBIOS Version	2.8
Embedded Controller Version	1.13
BIOS Mode	UEFI
BaseBoard Manufacturer	LENOVO
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.16299.371"
User Name	FAREAST\pullabhk
Time Zone	India Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.8 GB
Available Physical Memory	10.0 GB
Total Virtual Memory	31.8 GB
Available Virtual Memory	25.8 GB
Page File Space	16.0 GB
Page File	C:\pagefile.sys
Virtualization-based security	Running
Virtualization-based security Required Security Properties	Base Virtualization Support, Secure Boot
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot
Virtualization-based security Services Configured	Credential Guard
Virtualization-based security Services Running	Credential Guard
Device Encryption Support	Elevation Required to View

**Comment by davidebbo** [comment]
It's just a normal .NET app, and there hasn't been an update in a while. If it used to work for you and no longer does, I'd guess you have a general issue with your .NET install.

**Comment by davidebbo** [comment]
Closing for now, as the suspicion is a general .NET issue not related to this tool in particular.

**Comment by pvrk** [comment]
@davidebbo : Sorry. didn't understand the guidance here. Should I reinstall the .NET software?

**Comment by davidebbo** [comment]
If you verified that your .NET is generally hosed, then you'll need to fix that up. You can try this [forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?category=netdevelopment) if you need help.
