### ISSUE TITLE
Support Environments with proxy

### ISSUE THREAD

**Issue by f-bader** [projectkudu/ARMClient#43]
As of version 1.2.0.0 the armclient command does not support environments where a proxy server must be used to access the internet.

Even if the proxy is configured with `netsh winhttp set proxy` armclient does not use this setting.

It would be great if you could support this functionality in a later version of armclient.

**Comment by snobu** [comment]
Hmm, it should obey whatever gets specified in `ARMClient.exe.config` since it's a .NET console app.
Can you try that? - https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings

**Comment by f-bader** [comment]
Hi @snobu I tried that out this morning but had no luck.

I placed the `ARMClient.exe.config` file in the directory `C:\ProgramData\chocolatey\lib\ARMClient\tools\` but that didn't work.

Here is the configuration I used
```
<configuration>
  <system.net>
    <defaultProxy enabled="true">
      <proxy proxyaddress="http://proxyaddress:3128"/>
    </defaultProxy>
  </system.net>
</configuration>
```

I tried other variations of the config file as well.

At last I downloaded armclient directly and saved the file in the armclient folder in my download directory.
`C:\Users\USERNAME\Downloads\ARMCLient\ARMClient.exe.config`

I then used Process Monitor to check if armclient.exe uses the file. And for all I can tell it at least tries to use the data provided.

![armclient_processmonitor](https://user-images.githubusercontent.com/3834359/42259793-4224bfea-7f62-11e8-9897-9192682ac2f5.png)

Do you have any idea what could be wrong? Is there any setting for debug logging?

**Comment by snobu** [comment]
@davidebbo @ahmelsayed Any code changes lately that could result in proxy bypass?

**Comment by f-bader** [comment]
@snobu I try to login interactively with `armclient login`. So no verbose flag there. The UI is just plain white and I can see that the connection attempt (`netstat -an | findstr SYN`) is directly and not using the proxy.

If I use `armclient spn [tenantid] [appid] [appkey]` everything works as expected. 

Seems the proxy settings are only not working for the generated login UI.

**Comment by snobu** [comment]
Hmm that might call into the other binary the AADClient one, not sure. Try to add a .config for that one as well.

**Comment by f-bader** [comment]
I check with Process Monitor and found that the following ".config" files are checked
```
C:\Users\USERNAME\Downloads\ARMCLient\ARMClient.exe.config
C:\Users\USERNAME\Downloads\ARMCLient\ARMClient.exe.mda.config
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.config
```
I also added the proxy configuration to the machine.config, this should work for any .NET Application on the client. But sadly it still won't work.

I also created .exe.config file for every executable in the directory, also without success.

The .mda.config file should not do anything regarding proxy settings, as far as I understood "Managed Debugging Assistants".

**Comment by snobu** [comment]
I added HTTP proxy support (through `WebRequest.DefaultWebProxy`), looks like it affects all requests, project wide, including ADAL.NET, which is nice.

Checkout my `snobu-proxy` branch and build it or just download [this test build](https://nofile.io/f/E8TfPrM6Y0T/Debug-with-proxy-support.zip) for a quick run.

Usage:
```
set ARMCLIENT_PROXY=10.9.8.7:8080
armclient.exe login
```

I'll make a PR into master if @davidebbo greenlights this approach.

**Comment by snobu** [comment]
Scratch that. ADAL.NET still bypasses the proxy for the UI requests. Looking into it.

**Comment by snobu** [comment]
Looks like this isn't going to work with ADAL 2.x. [**Proxy support**](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/62a82c78b2a8504065f342309f8015dde8b9eccc/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/WebProxyProvider.cs#L47), was introduced fairly recently (ADAL 3.x). 

I remember attempting to port this over to ADAL 3.x last year but gave up due to the way refresh tokens are currently being used. It's probably a good idea to look at that again, it's also relatively straight forward to go to .NET Core after that hurdle.

**Comment by f-bader** [comment]
`armclient azlogin` worked even without the environment variable set on my Windows machine.
Most likely because it is using the default browser.
But the currently released version 1.2.0.0 (zip and chocolatey) has no support for this option. I used the `snobu-proxy` branch build you had uploaded.

**Comment by snobu** [comment]
The master branch has `armclient azlogin` so it must be an older binary up on choco. @davidebbo Can you push a release to choco at current HEAD?

**Comment by davidebbo** [comment]
Ok, just pushed a 1.3, but it can take time for Choco approval. I also uploaded it to https://github.com/projectkudu/ARMClient/releases/tag/v1.3. Can you verify that?

**Comment by f-bader** [comment]
Hi @davidebbo there is still no option for `azlogin`. I receive the error message `Parameter 'azlogin' is invalid!`. I checked the source code that you published and  there is the option for `azlogin` in the `Program.cs`.

Output of the `PrintUsage` 
![image](https://user-images.githubusercontent.com/3834359/42410635-0cb99942-81ed-11e8-855d-cd81517d31b1.png)

**Comment by snobu** [comment]
Not sure what's going on there, maybe your environment is mixing up assemblies, try to remove all older copies from your choco bin directory and start over. The 1.3.0 release does have `azlogin` in -

![image](https://user-images.githubusercontent.com/6472374/42410730-54582be2-81f7-11e8-8d44-3b44f953e4ed.png)

**Comment by snobu** [comment]
All good, ok to close this one now?

**Comment by f-bader** [comment]
Yes, thank you all very much.
