### ISSUE TITLE
Getting an error during installing Arm client

### ISSUE THREAD

**Issue by khatauli** [projectkudu/ARMClient#47]
C:\WINDOWS\system32>choco install armclient
Chocolatey v0.10.11
Installing the following packages:
armclient
By installing you accept licenses for the packages.
armclient not installed. The package was not found with the source(s) listed.
 Source(s): 'http://wanuget/bootstrap/nuget'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

**Comment by davidebbo** [comment]
Looks like you are using custom sources, and likely would fail any choco installations form the main feed. So very likely not related to ARMClient.
