### ISSUE TITLE
Add maintainers to the Chocolatey package

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMClient#52]
@suwatch @ahmelsayed right now I'm the only maintainer on https://chocolatey.org/packages/ARMClient, and it would be good to add you guys. I uploaded a version 1.4 yesterday with the latest bits, but someone else should be able to do it.

What are your Chocolatey IDs?

**Comment by suwatch** [comment]
My Chocolatey ID is **suwatch**.

**Comment by davidebbo** [comment]
Ok, you should get an invite email you need to approve.

BTW, I had to add a VERIFICATION.txt file (259be7183bcbe23b5dceec1a144b833ea4353186) to make Chocolatey happy (some new requirement.

You can close this issue once you approve the invite.

**Comment by suwatch** [comment]
I got confirmation of ARMClient maintainership.  Thank @davidebbo for taking care of this.

**Comment by olandese** [comment]
Nice!
