### ISSUE TITLE
Armclient Dogfood login and request is not working

### ISSUE THREAD

**Issue by ankisho** [projectkudu/ARMClient#54]
Hi Team,

Armclient login dogfood cmd is stopped working with below error:

`Welcome ankisho@microsoft.com (Tenant: f686d426-8d16-42db-81b7-ab578e110ccd)
Authentication failed because the remote party has closed the transport stream.
The underlying connection was closed: An unexpected error occurred on a send.
An error occurred while sending the request.`

I've tried to upgrade the armclient but issue still persist.

could you please expedite the fix for this issue ?

Regards,
Anand

**Comment by DevenWalia** [comment]
+1

**Comment by suwatch** [comment]
I beleived there was an PPE ARM on the day.  Please try again.

**Comment by DevenWalia** [comment]
Unfortunately, I am still facing the same issue, @suwatch Suwat

Attaching error trace

(env1) PS C:\Users\dewalia\Downloads\tbd> ARMClient.exe login Dogfood                                                                                                                                                                        Welcome dewalia@microsoft.com (Tenant: f686d426-8d16-42db-81b7-ab578e110ccd)
An existing connection was forcibly closed by the remote host
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
The underlying connection was closed: An unexpected error occurred on a send.
An error occurred while sending the request.
(env1) PS C:\Users\dewalia\Downloads\tbd>       
(env1) PS C:\Users\dewalia\Downloads\tbd> date                                                                                                                                                                                               
Monday, May 11, 2020 5:14:24 PM

**Comment by ankisho** [comment]
@suwatch : same issue is still there. could you please expedite the fix for this issue ?

**Comment by LTA-Thinking** [comment]
+1

Don't know if it is the same issue but I get this error in the sign in box when I try to log into DF:
AADSTS70008: The provided authorization code or refresh token has expired due to inactivity. Send a new interactive authorization request for this user and resource. 

Prod works fine.

**Comment by xiaomi7732** [comment]
+1 @LTA-Thinking I just experienced the same issue...

Is there a way to re-login?

**Comment by xiaomi7732** [comment]
Ping @suwatch, I am still blocked by this issue. Is there any insights?

**Comment by jp94** [comment]
+1 I am also having this issue.

**Comment by xiaomi7732** [comment]
I tried it again just now and it worked for me this time. Maybe its on the backend?

**Comment by abatishchev** [comment]
it's normal for Dogfood to be down from time to time, when it happens, please try to call ARM API from Postman or PowerShell to see if it's the backend or the client. most likely it's the former.
