### ISSUE TITLE
What is the latest version?

### ISSUE THREAD

**Issue by tech189** [projectkudu/ARMClient#60]
The releases page gives version 1.8 as the latest currently - https://github.com/projectkudu/ARMClient/releases/tag/v1.8

But the Chocolatey package is currently ahead at version 1.9 - https://community.chocolatey.org/packages/ARMClient

In addition, the GitHub release of 1.8 has no zip attached to the Assets - so the Scoop package is behind on the last version with a zip release (1.6)

**Comment by abatishchev** [comment]
I see Suwat just published both 1.8 and 1.9.

**Comment by tech189** [comment]
Ah good. However there's still no zip with binaries attached to those releases.

**Comment by abatishchev** [comment]
@suwatch could you please attach zipper binaries? Would they be authenticode signed? I can help to setup a build pipeline that would sign then with Microsoft Open Source certificate, if it's appropriate.

**Comment by abatishchev** [comment]
@suwatch ping on the binaries, please.

**Comment by suwatch** [comment]
You can get the binaries by downloading nupkg from https://community.chocolatey.org/packages/ARMClient -  click the download button on the right plane.   Rename the nupkg to zip files – the binaries are in that zip file under tools folder.    

Yes - @abatishchev  please help setup build pipeline to sign these.

**Comment by abatishchev** [comment]
I've added zipped binaries to the [v1.8](https://github.com/projectkudu/ARMClient/releases/tag/v1.8) and [v1.9](https://github.com/projectkudu/ARMClient/releases/tag/v1.9) releases.

I'll work on a build pipeline to do that little later, will probably produce v1.10 in coordination with @suwatch.
