### ISSUE TITLE
Support taking PUT payload from stdin

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMClient#7]
I've been thinking that scenarios would be easier in PowerShell is we take in the payload from stdin instead of (or as an alternative to?) using a switch. e.g., suppose you have the json payload in a $json variable.

You can't write: `ARMTemplate PUT /path -content $json`, because you're up against nearly unsolvable quoting issues. But you can write `$json | ARMTemplate PUT /path` as that avoids all the quoting issues. It's also simpler.

**Comment by suwatch** [comment]
Fix by 77975a1
