### ISSUE TITLE
How do you set the `ARMCLIENT_TENANT` environment variable correctly?

### ISSUE THREAD

**Issue by annatindall** [projectkudu/ARMClient#71]
I'm trying to log in using armclient with a user account that is a guest in a lot of different tenants. I only want to log into my home tenant, so tried setting the `ARMCLIENT_TENANT` env var following https://github.com/projectKudu/ARMClient/wiki/Login-and-Acquire-Tokens.

However, this did not work - the login flow still prompted me to login to all the tenants.

How exactly am I supposed to set this env var, and what do I set it to?

I was running from powershell and so used $env:ARMCLIENT_TENANT, and tried both the tenant ID and the domain name, but I'm not sure what's the correct approach from the docs.

**Comment by suwatch** [comment]
Fixed by https://github.com/projectkudu/ARMClient/commit/911b6b91c0a52025d7bab214dee0f6158501ee41
