### ISSUE TITLE
Create release page with compiled ARMClient

### ISSUE THREAD

**Issue by IlyaGrebnov** [projectkudu/ARMClient#8]
Guys, could you please create release page with compiled version of ARMClient for Windows? I am a bit lazy to build from source :)

**Comment by davidebbo** [comment]
The goal is to make it available via Chocolatey but we haven't done that yet. I suppose we could also have a download link, but I don't think GitHub supports that anymore (https://github.com/blog/1302-goodbye-uploads).

**Comment by IlyaGrebnov** [comment]
We could upload binaries to Azure blob or Amazon S3 :)

**Comment by davidebbo** [comment]
ARMClient is now available on Chocolatey (see my [post](http://blog.davidebbo.com/2015/01/azure-resource-manager-client.html)), which is easier than having to download the binaries. If you manually download them, you'll need to put them somewhere on your path, deal with updates, etc... Chocolatey takes care of all that.
