### ISSUE TITLE
Problem with command line parameters parsing

### ISSUE THREAD

**Issue by IlyaGrebnov** [projectkudu/ARMClient#9]
ARMClient.exe PUT subscriptions/26756605-1ad6-450f-b87f-6ccc2acd0ebc/resourceGroups/flowsrg?api-version=2014-04-01-preview -data @put_rg.json -verbose

Gives me "Parameter '-verbose' is invalid!" error.

**Comment by davidebbo** [comment]
Yes, it looks like this is buggy. If you change the order of `-data` and `-verbose`, it tells you that `-data` is invalid :)

**Comment by davidebbo** [comment]
@suwatch just fixed it.

**Comment by IlyaGrebnov** [comment]
Let me me verify :)

**Comment by suwatch** [comment]
Fix by https://github.com/projectkudu/ARMClient/commit/1e1b61982824129ff089e491b6b661ab8ef1bc4e
